# Generated by Django 5.2 on 2025-05-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_vinyl',
        ),
    ]
