# Generated by Django 5.2 on 2025-05-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
