# Generated by Django 5.2 on 2025-05-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='descriprion',
        ),
    ]
