# Generated by Django 5.1.7 on 2025-04-22 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedproduct',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['generalproduct', 'vinylrecord']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='trackedproduct',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_products', to='users.userprofile'),
        ),
    ]
