# Generated by Django 5.1.7 on 2025-05-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_trackedproduct_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed_authors',
            field=models.ManyToManyField(blank=True, related_name='followers', to='users.userprofile'),
        ),
    ]
