# Generated by Django 5.2 on 2025-05-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscribe_to_newsletter',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
