# Generated by Django 5.2 on 2025-05-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_subscribe_to_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscribe_to_newsletter',
        ),
    ]
