# Generated by Django 5.2 on 2025-05-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userprofile_subscribe_to_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Місячний план - 200грн/місяць'), ('yearly', 'Річний план - 2000грн/рік')], default='monthly', max_length=20),
        ),
    ]
