# Generated by Django 5.1.7 on 2025-04-22 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['generalproduct', 'vinylrecord']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
